spring.application.name=auth-service
server.port=8082

logging.level.root=INFO
logging.level.com.microecommerce.auth=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always

auth.google.issuer=https://accounts.google.com
auth.google.client-id=${GOOGLE_CLIENT_ID:replace-me.apps.googleusercontent.com}

auth.jwt.secret=change-this-secret-key-to-at-least-32-bytes-long
auth.jwt.expiration-seconds=3600
