spring.application.name=auth-service
server.port=8082

logging.level.root=INFO
logging.level.com.microecommerce.auth=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always
